### PR TITLE
Db hw climbsformountaineeringclub

### PR DESCRIPTION
**Pull request by olegarslanov**
HW

### CODE REVIEW

**Comment by geroget** [comment]
Hello Oleg, thank you for great job!
Your schema is generally clear, complies with the 3 NFs and is easy to read. The keys and relationships are correct, which means that you understand the basic theoretical rules for building a database model. 
The business document contains all the basic requirements and descriptions. You understand how to deal with many-to-many situation. Based on the document and schema I can understand the business process.

Some notes:
sponsor and club. Does your scheme mean that a sponsor can only donate to one club? 
I mean a situation where the business will grow and there will be more than one club. How will you manage this situation?it's better think ahead.

climber_sponsor
You have marked climber_id and sponsor_id as a compound PK. This means that the combination of these fields defines an UNIQUE string. This means that each sponsor can only donate to the same climber 1 time, right?
But if he wants to donate to the same climber again, how will you reflect that in your data? How do you keep a history of all donations?

The document has club_id in climber_sponcor, but not in the schema.

climber_climb. Mismatch between diagram and description in relationship. Same for climber_sponsor - club: mismatch between diagram and description in relationship. Same for Climb_route.

climber - climber_equipment should be 1:m instead of m:1.

Climber_climb is described twice in the document.

Not quite sure what the purpose of the Weather table is. Ok, how can you use it? Can you determine what the weather was like on a particular day of climbing? 

What is the purpose of putting route_difficulty in a separate table? I think it shouldn't break 3nf if you include it in the route table. Especially considering that in the sample data for the route table, you specified difficulty_level instead of route_difficulty_id. I hope I explained it clear.

**Comment by olegarslanov** [comment]
Hi Tatjana,

Firstly Thank You for good words, I tried and it is first my logical scheme in my life ... Yes I understand that with this schema I must add more things in the future, when it can be real schema
So I will correct the mistakes :)

**Comment by geroget** [comment]
Hi Oleg,
Please post a link to your git in learn. without it I can't review.

**Comment by olegarslanov** [comment]
Sorry I forgot do that ... now You can review :)

**Comment by geroget** [comment]
Hello Oleg,
thank you for your efforts.
Some notes:

sponsor and club. I would add a dridge sponsor_club table to avoid a lot of Nulls in the donation table. But your solution also makes sense. 

climber_climb. You added club_id to the model, but forgot to describe it in the document (club_id is missing).

I still can't figure out how to determine what the weather was on a particular climbing day. But ok, I'll see how you implement this in practice.

This PR is approved, you can merge the branch.

**Review by geroget — APPROVED** [review]

**Comment by olegarslanov** [comment]
Hi Tatjana,
Thanks for Your time ... I think You right on all points, I am only student now.
I will change climber_climb describing in the document (club_id is missing). 
Maybe we will come back to another two questions later ... thanks :)

**Pull request merged**
