### PR TITLE
SQL_SELECT_HW

### PR DESCRIPTION
**Pull request by olegarslanov**
Hi Tatjana,

It is my homework, please review it ... thanks in advance for Your time

### CODE REVIEW

**Comment by olegarslanov** [comment]
@geroget Hi Tatjana it is my second HW. Please review

**Comment by geroget** [comment]
Hello Oleg,
good job, thank you! But needs a little tweaking.

common notes:
- no schema name before table name.
- try to keep your queries simple.
- please leave comments in the code so I know what you are doing
- specify type of join (inner, left, ..)
- note the use of UPPER/LOWER when filter strings. It will help you not to lose rows
- try not to add unnecessary fields to the output. If you are asked to find movies. just specify the name of the appropriate column in the select row.
- it's a good practice to group by id not by name or title and bad practice to use ID in filter. 

Part1 task 1: you forgot about filter UPPER(c.name) = 'ANIMATION'. 
Part1 task 2: what is the goal of this subquery?
"join (select store_id, address, address2 FROM store s JOIN address a ON s.address_id = a.address_id) store_adr on store_adr.store_id = c.store_id"
you can just join them without subquery. result will be the same but query reads much easy

Part1 task 3: + for using CTE
Part1 task 4: I don't know what category_id = 7 or 16 means.
Query returns incorrect result. no need to group  by c.category_id, release_year is sufficient. and having expression is redundant.

Part1 task5: again, what does category_id = 11 mean? 
This is incorrect to use "distinct" with "first_name || ' ' || last_name as client". If you have clients with the same name you just combine them. And to avoid it you should group by client_id.
incorrect sequencies of joins: 
no need join payment with customer via customer_id. 
correct way: 	
from customer c
join rental r on c.customer_id = r.customer_id 
join payment p on r.rental_id = p.rental_id 
join inventory i on r.inventory_id = i.inventory_id
	
Part 2 task1: again I don't see name of employees and stories. their Ids tell me nothing
+ for the second solution

Part 2 task2 +
Part 3 V1-V2 showed all actors/actresses but requirement is show only those who didn't act for a longer period of time than the others. In general solutions are correct

**Comment by olegarslanov** [comment]
@geroget Hi Tatjana. I sent updated task. This time I made code better. I hope  :)
Maybe You can  share (if Yo have it) some algoritms for coding queries well :)

p.s. tommorow we have meeting 12.30. I will be not home, but I wil take with my laptop and we can meeting :)

**Comment by geroget** [comment]
Hello,
Please don't forget to put a link to your git in learn. without it I can't review.

**Comment by olegarslanov** [comment]
Ok ... I added link.
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by geroget** [comment]
I still don't see the link on the learn page. My comment is the last one.

**Comment by geroget** [comment]
approved

**Review by geroget — APPROVED** [review]

**Comment by olegarslanov** [comment]
ok, thanks  :)

**Pull request merged**
