### PR TITLE
SQL_DCL_HW

### PR DESCRIPTION
**Pull request by olegarslanov**
DCL HW

### CODE REVIEW

**Comment by olegarslanov** [comment]
@geroget Hi Tatjana. It is new HW. Not all I did like must be, but :)
Waiting for Your review and commentars what is wrong

**Comment by geroget** [comment]
Again you hardly comment on your code! This makes me think of cheating code..
-task2: Before you check if this works correctly, you should switch roles. please switch and check if you can manage select/insert/update operations;

task2/6, task3: add comments on what you are doing in each part of this code
task3 option2 - it would be better to combine all blocks into one function. in general it doesn't work, clients still don't have permissions to see their orders and payments

**Comment by olegarslanov** [comment]
@ Hallo Tatjana ! . Ok I did that. Please review. Thanks for Your help to do that :)

**Comment by geroget** [comment]
Approved. Please don't use translit for comments next time.

**Review by geroget — APPROVED** [review]

**Pull request merged**
