### PR TITLE
FinalTask_household_appliances_store

### PR DESCRIPTION
**Pull request by olegarslanov**
It is my Final Task

### CODE REVIEW

**Comment by olegarslanov** [comment]
@georget Hallo Tatjana. I finish Final task (chut ne prozeval, poterial 1.5 dnia iz 3 ... horoso cto odnokursniki podskazali, 7 task sdelan ne do konca... ne ochen znaju kak ego korektno sdelat ... postaralsja bolshe komentarijev). Please review

**Review by geroget — APPROVED** [review]

**Comment by geroget** [comment]
Hello Oleg, thank you for the really good job!

A couple of notes:
business document is incomplete
3nf violation (transitive dependency in product table prodact_model > product_brand)
to make the script in task 6 rerunnable, you can use anonymous blocks as usual.

Please don't write in transliteration, it's quite difficult to read 😒

**Comment by olegarslanov** [comment]
Hallo Tatjana. So I need correct that work? or not? 
Because it takes time ... and we have another HW and simulations tasks :)

**Comment by geroget** [comment]
Hello Oleg. No need to correct final task. Only if you want for yourself

**Comment by geroget** [comment]
Here is a simple and clear explanation of goal FK
 https://w3resource.com/sql/creating-and-maintaining-tables/foreign-key.php

**Pull request merged**
