### PR TITLE
 new dml HW

### PR DESCRIPTION
**Pull request by olegarslanov**
Hi Tatjana,

I sent to You my homework Nr.3 

Thanks in advance

### CODE REVIEW

**Comment by olegarslanov** [comment]
@georget It is my HW Nr.3

**Comment by geroget** [comment]
Hello Oleg,
good job!  You've completed all tasks, your comments allow to fully understand of logic, almost all scripts are rerunnable, and you've taken into account past comments.
Some comments: 
no need to hardcode of IDs. Your queries don't work for me because in my table the created film_ids, actor_Ids are different from yours. It's better to find that ID by name. INSERT INTO ... SELECT .... FROM. The same goes for address_id, customer_id, store_id.

"Alter any existing customer.." task: you need to combine that 2 queries into one.

Hardcode in delete queries. 
To do this code rerunnable you can use:
IF EXISTS(SELECT .. FROM..) DELETE FROM Your_table WHERE user_id= user_id

to insert new values in date fields it's better to use current_date function.

**Comment by olegarslanov** [comment]
Ok I understand that I did not to good ... thanks for good words :)
I hope now is much better :)

**Review by geroget — APPROVED** [review]

**Comment by geroget** [comment]
approved

**Comment by olegarslanov** [comment]
thanks :)

**Pull request merged**
